<?php
/**
* @file
* ShareCount Integration
*/

/**
 * Implements hook_menu().
 */
function shared_count_menu() {
  $items = array();
  $items['admin/config/services/shared-count-config'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shared_count_config_form'),
    'access arguments' => array('configure shared count'),
    'title' => t('Shared count configuration'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function shared_count_permission() {
  $permissions['configure shared count'] = array(
    'title' => t('Configure Settings for Shared Count'),
    'description' => t('Access to Shared Count configuration'),
    'restrict access' => TRUE,
  );
  return $permissions;
}

/**
* Shared Count Configuration form.
*/
function shared_count_config_form($form, $form_state) {
  $shared_count_plans = array(
    'https://free.sharedcount.com/' => t('Free'),
    'https://plus.sharedcount.com/' => t('Plus'),
    'https://business.sharedcount.com/' => t('Business'),
  );
  $form['shared_count_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Shared count API key'),
    '#default_value' => variable_get('shared_count_api_key', ''),
    '#required' => TRUE,
  );
  $form['shared_count_min_shares'] = array(
    '#type' => 'textfield',
    '#title' => t('Minimum number of shares'),
    '#description' => t('If your content has less than this minimum number of shares, the module going to set this value as the number of shares for your content'),
    '#default_value' => variable_get('shared_count_min_shares', 0),
    '#required' => TRUE,
  );
  $form['shared_count_plan'] = array(
    '#type' => 'radios',
    '#title' => t('Shared Count Plans'),
    '#default_value' => variable_get('shared_count_plan','https://free.sharedcount.com/'),
    '#options' => $shared_count_plans,
    '#description' => t('Select your shared count plan'),
  );
  return system_settings_form($form);
}

/**
* Shared Count Configuration form validate.
*/
function shared_count_config_form_validate($form, &$form_state) {
  if (!is_numeric($form_state['values']['shared_count_min_shares'])) {
    form_set_error('shared_count_min_shares',t('This field should be a number'));
  }
}

/**
* Implements hook_block_info().
*/
function shared_count_block_info() {
  $blocks = array();
  $blocks['share_count_block'] = array(
    'info' => t('Shared Count'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function shared_count_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'share_count_block':
    $block['subject'] = '';
    $block['content'] = shared_count_block_markup();
  }
  return $block;
}

/**
* Generete the markup for the share buttons.
*/
function shared_count_block_markup() {
  $settings = array(
    'shared_count_api_key' => variable_get('shared_count_api_key',''),
    'shared_count_min_shares' => variable_get('shared_count_min_shares', 0),
    'shared_count_request_domain' => variable_get('shared_count_plan', 'https://free.sharedcount.com/'),
  );
  drupal_add_js(array('setting' => $settings), array('type' => 'setting'));
  global $base_url;
  $path_alias = drupal_get_path_alias();
  $markup = '<aside class="shared-count-block">';
  $markup .= '<div class="total-shares">';
  $markup .= '<em class="shared-count"></em>';
  $markup .= '<div class="caption">' . t('Shares') . '</div></div>';
  $markup .= '<div  class="share-container">';
  $markup .= '<div  class="shared-count-primary-shares">';
  $markup .=  l(t('Share on Facebook'), 'https://www.facebook.com/sharer/sharer.php', array('external' => TRUE,'query' => array('u' => $base_url . '/' . $path_alias), 'attributes' => array('class' => array('shared-count-facebook'))));
  $markup .=  l(t('Share on Twitter'), 'https://twitter.com/home', array('external' => TRUE,'query' => array('status' => $base_url . '/' . $path_alias), 'attributes' => array('class' => array('shared-count-twitter'))));
  $markup .=  l(t('g+'), 'https://plus.google.com/share', array('external' => TRUE,'query' => array('url' => $base_url . '/' . $path_alias), 'attributes' => array('class' => array('shared-count-googleplus'))));
  $markup .= '<div class="shared-count-more-social-networks">' . t('more') . '</div>';
  $markup .= '</div><div class="shared-count-secondary-shares">';
  $markup .= l(t('Linkedin'),'https://www.linkedin.com/shareArticle', array('external' => TRUE, 'query' => array('url' => $base_url . '/' . $path_alias, 'title' => drupal_get_title(), 'mini' => TRUE), 'attributes' => array('class' => array('shared-count-linkedin'))));
  $markup .= l(t('Stumbleupon'),'https://www.stumbleupon.com/submit', array('external' => TRUE, 'query' => array('url' => $base_url . '/' . $path_alias, 'title' => drupal_get_title()), 'attributes' => array('class' => array('shared-count-stumbleupon'))));
  $markup .= l(t('Pinterest'),'https://pinterest.com/pin/create/button/', array('external' => TRUE, 'query' => array('url' => $base_url . '/' . $path_alias), 'attributes' => array('class' => array('shared-count-pinterest'))));
  $markup .= '</div></div> </aside>';
  return $markup;
}
